trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'

  # Azure Details
  azureServiceConnection: 'azure-connection'
  webAppName: 'abhi-react-webapp'

stages:

# =====================================================
# STAGE 1 : BUILD
# =====================================================
- stage: Build
  displayName: 'Build React App'

  jobs:
  - job: BuildJob
    displayName: 'Install and Build'

    steps:

    # Install Node.js

    # Install dependencies
        
    - task: UseNode@1
      inputs:
        version: '18.x'
      displayName: 'Use Node.js 18'

    - script: |
        node -v
        npm -v
        which node
      displayName: 'Verify Node Version'


    - script: |
        npm install
      displayName: 'Install Dependencies'

    # Build application
    - script: |
        npm run build
      displayName: 'Build React Application'

    # Verify build folder
    - script: |
        ls -la
        ls -la build
      displayName: 'Verify Build Output'

    # Copy build files
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
      displayName: 'Copy Build Files'

    # Publish artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
        ArtifactName: 'react-build'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'


# =====================================================
# STAGE 2 : DEPLOY
# =====================================================
- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build

  jobs:
  - deployment: DeployReactApp
    displayName: 'Deploy React App'

    environment: 'production'

    strategy:
      runOnce:
        deploy:
          steps:

          # Download artifact
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'react-build'
              downloadPath: '$(Pipeline.Workspace)'
            displayName: 'Download Artifact'

          # Deploy to Azure App Service
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/**/*.zip'
            displayName: 'Deploy to Azure Web App'

