# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'

  # Azure Details
  azureServiceConnection: 'azure-connection'
  webAppName: 'my-react-webapp'

stages:

# =====================================================
# STAGE 1 : BUILD
# =====================================================
- stage: Build
  displayName: Build React App

  jobs:

  

  - job: BuildJob
    displayName: Install and Build

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: Install Node.js

    - script: |
       npm install react-scripts --save
      displayName: Install reactscript 

    - script: |
        npm install
      displayName: Install Dependencies

    

    - script: |
        npm run build
      displayName: Build React Application

    - script: |
          npm audit fix --force
      displayName: force fix vulnerablilities      

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Copy Build Files

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'react-build'
      displayName: Publish Artifact



# =====================================================
# STAGE 2 : DEPLOY
# =====================================================
- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build

  jobs:
  - deployment: DeployReactApp
    displayName: Deploy React App

    environment: production

    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: current
              downloadType: single
              artifactName: react-build
              downloadPath: '$(Pipeline.Workspace)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: webAppLinux
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/react-build'
            displayName: Deploy to Azure Web App